[package]
name = "hub75-pio"
version = "0.1.0"
edition = "2021"
description = "A HUB75 driver for RP2040. Utilizes PIO and DMA to achieve zero CPU overhead."
license = "MIT"

[dependencies]
pio-proc = "0.2"
pio = "0.2.0"
libm = "0.2"
fixed = "1.23.1"

defmt = { version = "0.3", optional = true }
defmt-rtt = { version = "0.4", optional = true }

embedded-graphics = "0.8"
rp-pac = "6.0.0"
embassy-rp = { version = "0.3.0", features = ["rp2040", "unstable-pac", "time-driver", "critical-section-impl"] }

[patch.crates-io]
embassy-rp = { git = "https://github.com/embassy-rs/embassy.git", rev = "a991cd6a8d4d8a306b225548f4ab31858d6a0535" }

[features]
defmt = [
    "dep:defmt",
    "dep:defmt-rtt",
    "embassy-rp/defmt",
]